from . import courier_booking
from . import shipping_mode
from . import shipping_route
from . import route_line
from . import shipping_suggestion
from . import delivery_agent
from . import courier_tracking
from . import customer_complaint
from . import assign_agent_wizard
from . import courier_delivery_wizard
from . import mode_wise_report
from . import route_performance_report
from . import number_of_complaints_report
from . import type_wise_report
from . import agent_resolution_report