{
    'name': 'Task',
    'version': '18.0.1.0',
    'summary': 'This is task odoo',
    'description': """    """,
    # 'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['base','sale_management','contacts', 'stock', 'purchase'],
    'data': [
        "data/purchase_order_sequence.xml",
        "views/sale_order_report_view.xml",
        "views/stock_picking_delivery_report.xml",
        "views/sale_order_view.xml",
        "views/stock_picking_view.xml",
        # "views/purchase_order_view.xml",
        "views/res_config_settings_view.xml",
        "views/res_company_view.xml",
        "views/account_move_view.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}