{
    'name': 'Courier Management System',
    'version': '18.0.1.0',
    'summary': 'Courier Management System',
    'description': """    """,
    'depends': ['base', 'product','mail','account'],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "demo/shipping_mode_demo_data.xml",
        "report/courier_booking_templates.xml",
        "report/courier_booking_report.xml",
        "views/courier_booking_view.xml",
        "views/shipping_mode_view.xml",
        "views/shipping_route_view.xml",
        "views/delivery_agent_view.xml",
        "views/courier_tracking_view.xml",
        "views/customer_complaint_view.xml",
        "views/route_line_view.xml",
        "views/shipping_suggestion_view.xml",
        "views/assign_agent_wizard_view.xml",
        "views/courier_delivery_wizard_view.xml",
        "views/customer_complaint_show_view.xml",
        "views/mode_wise_report_view.xml",
        "views/route_performance_report_view.xml",
        "views/number_of_complaints_report_view.xml",
        "views/type_wise_analysis_report.xml",
        "views/agent_resolution_report_view.xml",
        "views/menus.xml",
    ], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}