{
    'name': 'Hotel Management System',
    'version': '18.0.1.0',
    'summary': 'This is the hotel management system...',
    'description': """    """,
    # 'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['base', 'hr', 'account', 'contacts', 'sale_management'],
    'data': [
        "security/ir.model.access.csv", 
        "report/reservation_report_templates.xml",
        "report/reservation_reports.xml",
        "data/reservation_data.xml",
        "views/hotel_management_view.xml",
        "views/hotel_room_view.xml",
        "views/hotel_guest_view.xml",
        "views/hotel_reservation_view.xml",
        "views/extra_charges_view.xml",
        "views/hotel_partner_view.xml",
        "views/housekeeping_request_view.xml",
        "views/menus.xml",
    ], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}