from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import purchase_order
from . import res_partner
from . import res_config_settings
from . import res_company
from . import account_move
from . import stock_move