from . import courier_booking
from . import shipping_mode
from . import shipping_route
from . import route_line
from . import shipping_suggestion
from . import delivery_agent
from . import courier_tracking
from . import customer_complaint
from . import account_move
from . import courier_tags
from . import cust_wizard_agent