{
    'name': 'Hotel Management',
    'version': '18.0.1.0',
    'summary': 'This is the hotel management system',
    'description': """    """,
    # 'category': 'Accounting/Accounting',
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': [],
    'data': [
        "security/ir.model.access.csv",
        "data/booking_data.xml", 
        "report/booking_reports_templates.xml",
        "report/booking_reports.xml",
        "wizard/book_room_wizard.xml",
        "views/hotel_management_view.xml",
        "views/room_view.xml",
        "views/guest_view.xml",
        "views/booking_view.xml",
        "views/extra_charges_view.xml",
        "views/menus.xml",  
    ], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}