{
    'name': 'Hotel',
    'version': '18.0.1.0',
    'summary': 'This is the hotel...',
    'description': """    """,
    'depends': ['base', 'account'],
    'data': [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/hotel_view.xml",
        "views/room_view.xml",
        "views/room_type_view.xml",
        "views/room_price_view.xml",
        "views/room_specifications_view.xml",
        "views/hotel_amenities_view.xml",
        "views/room_season_view.xml",
        "views/hotel_service_view.xml",
        "views/hotel_policy_view.xml",
        "views/hotel_booking_view.xml",
        "views/guest_view.xml",
        "views/hotel_configurations_view.xml",
        "views/room_availability_wizard_view.xml",
        "views/room_wizard_view.xml",
        "views/booking_room_line_view.xml",
        "views/room_pricelist_view.xml",
        "views/staff_view.xml",
        "views/maintenance_type_view.xml",
        "views/planning_view.xml",
        "views/staff_log_view.xml",
        "views/maintenance_service_view.xml",
        "views/report_issue_view.xml",
        "views/restraunt_view.xml",
        "views/restraunt_food_view.xml",
        "views/report_issue_show_view.xml",
        "views/housekeeping_checklist_view.xml",
        "views/restraunt_order_view.xml",
        "views/menus.xml",
    ], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}