from . import sale_order
from . import product_template
from . import stock_picking
from . import hr_timesheet
from . import crm_lead
from . import account_move
from . import sale_order_template
from . import hr_leave
from . import stock_move
from . import project_task
from . import product_product
from . import hr_employee
from . import purchase_order
from . import mail_activity