{
    'name': 'Courier',
    'version': '18.0.1.0',
    'summary': 'Courier Management',
    'description': """    """,
    'depends': ['base', 'mail'],
    'data': [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/mail_template_data.xml",
        "views/courier_request_view.xml",
        "views/courier_tag_view.xml",
        "views/courier_type_view.xml",
        "views/courier_categories.xml",
        "views/courier_priorities_view.xml",
        "views/courier_weight_price_rule_view.xml",
        "views/courier_dimension_price_rule.xml",
        "views/courier_distance_price_rule_view.xml",
        "views/menus.xml",
    ], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}