{
    'name': 'Courier Management System',
    'version': '18.0.1.0',
    'description': """ Courier Management System """,
    'depends': ['account','mail','project','account_payment'],
    'data':[   
         'security/courier_security.xml',
         'security/ir.model.access.csv',
          'report/complaints_graph.xml',
         'data/booking_sequence.xml',
         'view/courier_booking.xml',
         'view/shipping_mode.xml',
         'view/shipping_route.xml',
         'view/delivery_agent.xml',
         'view/courier_tracking.xml',
         'view/courier_tags.xml',
         'view/customer_complaint.xml',
         'view/delivery_wizard.xml',
         'view/user_complaint.xml',
         'view/agent_delivery_wizard.xml',
        'report/courier_receipt_template.xml',
        'report/courier_receipt_report.xml',    
         'demo/demo_data.xml',
        'report/modes_graph.xml',
         'report/routes_graph.xml',
         'report/complaints_graph.xml',
         'report/types_graph.xml',
         'report/agent_graph.xml',
         'view/menu_items.xml',
        ],
      'assets': {
     'web.assets_backend': [
            'courier_management/static/src/style.css',
              ],
    },
        'application': True,    
        'installable': True,
        'license': 'LGPL-3'
}