{
    'name': 'Mine',
    'version': '18.0.1.0',
    'summary': 'This is mine task odoo',
    'description': """    """,
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['base','sale_management', 'hr_holidays', 'contacts', 'hr_timesheet', 'product', 'stock', 'crm', 'project', 'hr', 'hr_contract', 'purchase'],
    'data': [
       "views/sale_order_view.xml",
       "views/product_template_view.xml",
       "views/stock_picking_view.xml",
       "views/hr_timesheet_view.xml",
       "views/crm_lead_view.xml",
       "views/contacts_default_list_view.xml",
       "views/account_move_view.xml",
       "views/sale_order_template_view.xml",
       "views/hr_leave_view.xml",
       "views/stock_move_view.xml",
       "views/project_task_view.xml",
       "views/product_product_view.xml",
       "views/hr_employee_view.xml",
       "views/purchase_order_view.xml",
       "views/mail_activity_view.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}